swc-installation-test-2.py: Add remote check configuration
On Wed, Mar 11, 2015 at 03:08:15PM -0700, Piotr Banaszkiewicz wrote [1]:
> Maybe add workshop-template/requirements.txt (not necessarily a
> Python dependencies file) that's read by installation testing script
> and adjusts CHECKS entries accordingly?

The old CHECKS approach didn't work very well, because many
instructors would forget to edit CHECKS and learners would be confused
when they failed checks for packages that they didn't actually need
(but which were still listed in CHECKS) [2,3,4,5].  This commit makes:

  $ ./swc-installation-test-2.py

a no-op.  Users will either have to explicitly specify checks on the
command line:

  $ ./swc-installation-test-2.py virtual-editor

or point the tester at an instructor-provided config:

  $ ./swc-installation-test-2.py --url https://swcarpentry.github.io/2015-11-09-abc/lessons.json

Because dependencies for a given lesson can be tricky and are shared
by all lesson consumers, it offloads the bulk of the
requirement-listing to lesson maintainers.  Once that work is done,
instructors can just list out the lessons they're covering (which is
also useful for tools like AMY [6] who would like an automatic way to
determine what is being taught).

SWC generally prefers YAML to JSON, but I've gone with JSON here to
stick with stock Python 2.6+ support.  I've also changed some
or_dependency definitions from tuples to lists so I can mutate them
with .remove().

The tuple cast when setting minimum_version from the JSON lets us
avoid:

  TypeError: unorderable types: tuple() < list()

when doing the version comparison.

[1]: https://github.com/numfocus/gsoc/issues/3#issuecomment-78383271
[2]: https://github.com/swcarpentry/workshop-template/issues/136
[3]: https://github.com/swcarpentry/workshop-template/issues/180
[4]: https://github.com/swcarpentry/workshop-template/issues/181
[5]: https://github.com/swcarpentry/workshop-template/issues/258
[6]: https://github.com/swcarpentry/amy